site_name: ã‚¢ãƒ«ãƒ•ã‚¡ã‚¹ã®ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
copyright: Copyright &copy; 2021-2022 Alphaus Cloud. All rights reserved.

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  features:
  - navigation.tabs
  - navigation.expand

nav:
- 'ãƒ›ãƒ¼ãƒ ':
  - 'index.md'
  - 'Identityã¨Access Management': 'iam.md'
  - 'Ripple ğŸ¡¥': 'https://docs.alphaus.cloud/v/ripple/'
  - 'Wave ğŸ¡¥': 'https://docs.alphaus.cloud/v/wave/'
  - 'WavePro ğŸ¡¥': 'https://docs.alphaus.cloud/v/projp/'
  - 'Aqua ğŸ¡¥': 'https://docs.alphaus.cloud/v/aqua/'
  - 'ãƒ˜ãƒ«ãƒ—ã‚»ãƒ³ã‚¿ãƒ¼ ğŸ¡¥': 'https://help.alphaus.cloud/ja/'
  - 'å…ˆã®ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ ğŸ¡¥': 'https://docs.alphaus.cloud/v/ripple/'
  - 'ã‚·ã‚¹ãƒ†ãƒ ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ ğŸ¡¥': 'https://status.alphaus.cloud/'
- 'Blue API':
  - 'blueapi/overview.md'
  - 'blueapi/authentication.md'
  - 'CLI: bluectl': 'blueapi/bluectl.md'
  - 'APIs':
    - 'blueapi/apis/org.md'
    - 'blueapi/apis/kvstore.md'
    - 'blueapi/apis/iam.md'
    - 'blueapi/apis/cost.md'
  - 'blueapi/client-sdks.md'

extra:
  alternate:
  - name: English
    link: /docs/
    lang: en
  - name: æ—¥æœ¬èª
    link: /docs-ja/
    lang: ja

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true 
